default: &default
  sv_base_url: http://malmo.se/
  site_search_url: http://s1.malmo.se
  site_search_ac_url: http://s1.malmo.se/search/autocomplete
  asset_host: //assets.malmo.se/external/v4/
  ua_external_account: 'UA-331614-1'
  ua_internal_account: 'UA-1659147-1'

development: &development
  <<: *default
  site_search_url: http://www.local.malmo.se:3000
  site_search_ac_url: http://www.local.malmo.se:3000/search/autocomplete
  asset_host: http://www.local.malmo.se:3001/assets/
  ua_external_account: 'UA-19475063-1'
  ua_internal_account: 'UA-19475064-1'

staging:
  <<: *default
  sv_base_url: http://www.test.malmo.se/
  asset_host: //assets.malmo.se/external/v4-staging/
  ua_external_account: 'UA-19475063-1'
  ua_internal_account: 'UA-19475064-1'

production:
  <<: *default
