default: &default
  sv_base_url: https://komin.malmo.se/
  site_search_url: //webapps06.malmo.se/dashboard/search
  site_search_ac_url: //webapps06.malmo.se/dashboard/search/autocomplete
  asset_host: //assets.malmo.se/internal/v4/
  ua_account: 'UA-1659147-1'
  dashboard_base_url: "https://webapps06.malmo.se/dashboard/"

development: &development
  <<: *default
  sv_base_url: http://www.local.malmo.se:3000/
  site_search_url: http://www.local.malmo.se:3000/search
  site_search_ac_url: http://www.local.malmo.se:3000/search/autocomplete
  asset_host: http://www.local.malmo.se:3001/assets/
  ua_account: 'UA-19475064-1'
  dashboard_base_url: "http://www.local.malmo.se:3000/"

staging:
  <<: *default
  sv_base_url: https://komin.test.malmo.se/
  site_search_url: //webapps06.malmo.se/dashboard-test/search
  site_search_ac_url: //webapps06.malmo.se/dashboard-test/search/autocomplete
  asset_host: //assets.malmo.se/internal/v4-staging/
  ua_account: 'UA-19475064-1'
  dashboard_base_url: "https://webapps06.malmo.se/dashboard-test/"

production:
  <<: *default
