# File must be present, but is not used
default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_swedish_ci
  host: localhost
  pool: 20
  username:
  password:
  database:

development:
  <<: *default
